POST http://localhost:5000/api/xerox
Content-Type: application/json

{
    "printerName": "EPSON L3210 Series",
    "copies": 1
}

###
GET http://localhost:5000/api/printers

###
GET http://localhost:5000/api/xerox/check-scanner
Content-Type: application/json

### Get Preview Scan
GET http://localhost:5000/api/xerox/preview
Content-Type: application/json

### Get Available Printers
GET http://localhost:5000/api/printers
Content-Type: application/json

### Test Xerox Copy
POST http://localhost:5000/api/xerox
Content-Type: application/json

{
    "printerName": "EPSON L3210 Series",
    "copies": 1
}


